name: Run test 

env:
  OS: ubuntu-latest
  
on:
  push

jobs:
  install_dependency:
    runs-on: ubuntu-latest
    steps:
      - name: "sfvdsvsdfv"
        run: ls -la
      
  run_test:
    runs-on: ubuntu-latest
    needs: install_dependency
    steps:
      - name: "fdsfdsbvdsgb"
        run: echo "fsvsdfkhvbsdkjfhv"
