name: Maven Package

on: [push]

jobs:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
      - run: curl -s https://aerokube.com/cm/bash  | bash
      - run: chmod +x ./cm
      - run: ./cm selenoid start --vnc
      - run: ./cm selenoid-ui start
      
