name: Run test 

env:
  OS: "ubuntu-latest"
  
on:
  push

jobs:
  install_dependency:
    runs-on: $OS
    steps:
      - name: "sfvdsvsdfv"
        run: echo "Hello world!"
      
  run_test:
    runs-on: $OS
    steps:
      - name: "fdsfdsbvdsgb"
        run: echo "fsvsdfkhvbsdkjfhv"
