name: Run test 

env:
  OS: ubuntu-latest
  
on: push

jobs:
  install_dependency_and_run_test:
    runs-on: ubuntu-latest
    steps:
#       - name: "Скачиваем селенойд"
#         run: curl -s https://aerokube.com/cm/bash  | bash
#       - name: "Даем права на запуск селенойда"
#         run: chmod +x ./cm
#       - name: "Запускаем selenoid"
#         run: ./cm selenoid start --vnc
#       - name: "Запускаем selenoid-ui"
#         run: ./cm selenoid-ui start
      - name: "Используем main репозиторий"
        uses: actions/checkout@v1
      - name: "Запускаем тесты"
        run: mvn clean test
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
